################################
## Airflow Metadata Secret
#################################
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: {{ .Values.releaseStage }}-airflow-airflow-metadata
#   namespace: airflow
#   labels:
#     tier: airflow
#     release: {{ .Release.Name }}
#     chart: {{ .Chart.Name }}
#     heritage: {{ .Release.Service }}
#   annotations:
#     "helm.sh/hook": "pre-install"
#     "helm.sh/hook-delete-policy": "before-hook-creation"
#     "helm.sh/hook-weight": "0"
# spec:
#   refreshInterval: 1h
#   secretStoreRef:
#     kind: SecretStore
#     name: {{ .Values.releaseStage }}-kubernetes-secretstore
#   data:
#     - secretKey: connection
#       remoteRef:
#         property: METADATA_CONNECTION_URL 
#         key: {{ .Values.releaseStage }}-airflow-secret
