############################################
## Airflow Webserver Flask Secret Key Secret
############################################
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.releaseStage }}-airflow-webserver-secret-key
  namespace: airflow
  labels:
    tier: airflow
    component: webserver
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook-weight": "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: {{ .Values.releaseStage }}-kubernetes-secretstore
  data:
    - secretKey: webserver-secret-key
      remoteRef:
        property: WEBSERVER_SECRET_KEY
        key: WEBSERVER_SECRET_KEY
