###################################################
## SecretStore for Kubernetes
###################################################
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.releaseStage }}-kubernetes-secretstore
  namespace: airflow
spec:
  provider:
    kubernetes:
      remoteNamespace: airflow
      server: https://kubernetes.default.svc
      auth:
        serviceAccount:
          name: {{ .Values.releaseStage }}-airflow-store
