###################################################
## SecretStore for Kubernetes
###################################################
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.releaseStage }}-kubernetes-secretstore
  namespace: airflow
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook-weight": "0"
spec:
  provider:
    kubernetes:
      remoteNamespace: airflow
      server:
        url: https://kubernetes.default.svc
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: {{ .Values.releaseStage }}-airflow-store
