###################################################
## RoleBinding for reading secrets
###################################################
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-secrets
  namespace: airflow
subjects:
  - kind: ServiceAccount
    name: {{ .Values.releaseStage }}-airflow-store
    namespace: airflow
roleRef:
  kind: ClusterRole
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io
