###################################################
## Airflow Store Assume Role ServiceAccount
###################################################
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ .Values.releaseStage }}-airflow-store
  namespace: airflow
  labels:
    tier: airflow
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    {{- with .Values.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook-weight": "0"
